// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: actions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAction = `-- name: CreateAction :one

INSERT INTO actions (id, created_at, updated_at, name, description, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, user_id, name, description, recurrance_window, is_calibrating, created_at, updated_at
`

type CreateActionParams struct {
	Name        string
	Description sql.NullString
	UserID      uuid.UUID
}

// ----------CREATE Section - START-------------
// Create Action entity
func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (Action, error) {
	row := q.db.QueryRowContext(ctx, createAction, arg.Name, arg.Description, arg.UserID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.RecurranceWindow,
		&i.IsCalibrating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
