name: cd

on:
  push:
  # pull_request:
  #   types: [closed]
  #   branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  push-images:
    name: Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Read versions from file
        id: vars
        run: |
          export $(cat VERSION | xargs)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "DB_MIGRATION_VERSION=$DB_MIGRATION_VERSION" >> $GITHUB_ENV

      - name: Build shinko-app image
        uses: redhat-actions/buildah-build@v2
        with:
          image: shinko-app
          tags: latest ${{ env.APP_VERSION }} ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      - name: Build shinko-db-migration image
        uses: redhat-actions/buildah-build@v2
        with:
          image: shinko-db-migration
          tags: latest ${{ env.DB_MIGRATION_VERSION }} ${{ github.sha }}
          context: ./sql
          containerfiles: |
            ./sql/Containerfile

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push shinko-app image
        run: |
          podman tag shinko-app:latest quay.io/${{ secrets.QUAY_USERNAME }}/shinko-app:latest
          podman tag shinko-app:latest quay.io/${{ secrets.QUAY_USERNAME }}/shinko-app:${{ env.APP_VERSION }}
          podman push quay.io/${{ secrets.QUAY_USERNAME }}/shinko-app:latest
          podman push quay.io/${{ secrets.QUAY_USERNAME }}/shinko-app:${{ env.APP_VERSION }}

      - name: Push shinko-db-migration image
        run: |
          podman tag shinko-db-migration:latest quay.io/${{ secrets.QUAY_USERNAME }}/shinko-db-migration:latest
          podman tag shinko-db-migration:latest quay.io/${{ secrets.QUAY_USERNAME }}/shinko-db-migration:${{ env.DB_MIGRATION_VERSION }}
          podman push quay.io/${{ secrets.QUAY_USERNAME }}/shinko-db-migration:latest
          podman push quay.io/${{ secrets.QUAY_USERNAME }}/shinko-db-migration:${{ env.DB_MIGRATION_VERSION }}
