name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      
      - name: Run tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...

      - name: exit
        run: (exit 0)
    
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Style check
        run: test -z $(go fmt ./...)

      
      - name: Run Lint check
        run: staticcheck ./...

  build:
    - name: Set up Podman
        uses: containers/podman-action@v2

    - name: Build app Container image
      run: podman build -t shinko-app -f Containerfile .

    - name: Build migrations Container image
      run: podman build -t shinko-db-migration -f Containerfile ./sql/.

    - name: Verify app Container image
      run: podman images | grep shinko-app

    - name: Verify migrations Container image
      run: podman images | grep shinko-db-migration
